// <auto-generated />
namespace CalendarApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedstartDatestartTimeendDateendTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedstartDatestartTimeendDateendTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201610091624398_added startDate, startTime, endDate, endTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
