// <auto-generated />
namespace CalendarApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class putstartandendbackasdatafields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(putstartandendbackasdatafields));
        
        string IMigrationMetadata.Id
        {
            get { return "201610091655133_put start and end back as data fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
